name: fskeleton
description: Input Barang Mobile App
publish_to: none
version: 1.0.4+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  amazon_cognito_identity_dart_2: ^3.6.5
  cached_network_image: ^3.2.3
  camera: ^0.10.5+5
  collection: ^1.16.0
  cupertino_icons: ^1.0.8
  device_info_plus: ^11.5.0
  dio: ^5.4.0
  file_picker: ^10.2.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_html: ^3.0.0
  flutter_inappwebview: ^6.1.5
  flutter_lints: ^6.0.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.1.1
  flutter_secure_storage: ^10.0.0-beta.4
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^3.0.0
  go_router: ^15.2.3
  google_fonts: ^6.2.1
  html: ^0.15.6
  http: ^1.1.0
  image: ^4.0.17
  image_picker: ^1.1.2
  intl: ^0.20.2
  json_annotation: ^4.8.0
  mime: ^2.0.0
  package_info_plus: ^8.3.0
  path: ^1.9.1
  path_provider: ^2.0.15
  permission_handler: ^12.0.0+1
  pretty_dio_logger: ^1.4.0
  recase: ^4.1.0
  shared_preferences: ^2.2.3
  url_launcher: ^6.1.7
  webview_flutter: ^4.4.2
  webview_flutter_android: ^4.7.0
  webview_flutter_wkwebview: ^3.10.2
  win32: ^5.5.3

dev_dependencies:
  build_runner: ^2.4.12
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  json_serializable: ^6.5.4
  mocktail: ^1.0.4

dependency_overrides:
  http: ^1.1.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - .env
    - .env.dev
    - .env.prod
    - assets/images/
    - assets/
