name: fskeleton
description: Input Barang Mobile App
publish_to: none
version: 1.0.4+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  cached_network_image: ^3.2.3
  camera: ^0.10.5+5
  collection: ^1.16.0
  cupertino_icons: ^1.0.8
  device_info_plus: ^11.5.0
  dio: ^5.4.0
  file_picker: ^10.2.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_lints: ^6.0.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.1.1
  flutter_secure_storage: ^10.0.0-beta.4
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.1
  go_router: ^15.2.3
  google_fonts: ^6.2.1
  hooks_riverpod: ^2.4.9
  image_picker: ^1.1.2
  intl: ^0.20.2
  json_annotation: ^4.9.0
  package_info_plus: ^8.3.0
  path: ^1.9.1
  path_provider: ^2.0.15
  permission_handler: ^12.0.0+1
  pretty_dio_logger: ^1.4.0
  shared_preferences: ^2.2.3
  win32: ^5.5.3

dev_dependencies:
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  json_serializable: ^6.9.5

flutter:
  generate: true
  uses-material-design: true
  assets:
    - .env
    - .env.dev
    - .env.prod
    - assets/images/
    - assets/
